repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/ansible/ansible-lint
    rev: v6.21.1
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        args: [--fix, -c, .ansible-config]
